# Generated by Django 5.1 on 2024-08-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('hire_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['manager'], name='employees_e_manager_278e0e_idx')],
            },
        ),
    ]
