# Generated by Django 5.1.6 on 2025-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
