# Generated by Django 5.1.6 on 2025-03-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
    ]
